frequency: "Daily"
start_date_year: 2024
start_month_year: 1
start_day_year: 1
retries: 1
retry_delay: 5
schedule_interval: '@daily'
catchup: False 

use_kafka_sensor: False
kafka_topic: 'your_kafka_topic'
kafka_bootstrap_servers: ['localhost:9092']
kafka_group_id: 'your_group_id'
kafka_poke_interval: 30
kafka_timeout: 600

