name: '<PLACEHOLDER_NAME_HERE>'
version: '1.0.0'
profile: 'my_profile'

source-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]

models:
  <PLACEHOLDER_NAME_HERE>:
    staging:
      +materialized: view
    marts:
      +materialized: table
